#!/usr/bin/env bash
#
# Install the honcho and honcho-deriver systemd --user units on this host.
#
# Idempotent: re-running is safe. It:
#   - resolves the repo root and the honcho module directory
#   - renders the runtime env file at ~/.config/1215-vps/honcho.env from
#     stack/prototype-local/.env (and fails if that file is missing)
#   - renders the two .service units from the committed .in templates,
#     substituting the absolute paths, and copies them to
#     ~/.config/systemd/user/
#   - runs `systemctl --user daemon-reload`
#
# It does NOT enable or start the units. Do that explicitly:
#   systemctl --user enable --now honcho honcho-deriver
#
# Prerequisites:
#   - modules/honcho submodule is checked out
#   - `uv` is on PATH (the user-rule mandate; verified via `uv --version`)
#   - stack/prototype-local/.env contains OPENROUTER_API_KEY and
#     POSTGRES_PASSWORD

set -Eeuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"
honcho_dir="${repo_root}/modules/honcho"
env_source="${repo_root}/stack/prototype-local/.env"

config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"
systemd_user_dir="${config_home}/systemd/user"
honcho_env_dir="${config_home}/1215-vps"
honcho_env_file="${honcho_env_dir}/honcho.env"

if [[ ! -d "${honcho_dir}" ]]; then
  echo "ERROR: honcho module not checked out at ${honcho_dir}." >&2
  echo "Run: git submodule update --init modules/honcho" >&2
  exit 1
fi
if [[ ! -f "${env_source}" ]]; then
  echo "ERROR: missing ${env_source}; run stack/prototype-local/scripts/init_env.py first." >&2
  exit 1
fi
if ! command -v uv >/dev/null 2>&1; then
  echo "ERROR: \`uv\` not found on PATH." >&2
  exit 1
fi
uv_bin="$(command -v uv)"

mkdir -p "${systemd_user_dir}" "${honcho_env_dir}"
chmod 0700 "${honcho_env_dir}"

# -- Render ~/.config/1215-vps/honcho.env --------------------------------------
# Parse the stack .env (KEY=VALUE lines only; comments ignored).
postgres_password=""
openrouter_api_key=""
honcho_database_name="honcho"
while IFS= read -r line; do
  [[ "${line}" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line//[[:space:]]/}" ]] && continue
  key="${line%%=*}"
  value="${line#*=}"
  case "${key}" in
    POSTGRES_PASSWORD) postgres_password="${value}" ;;
    OPENROUTER_API_KEY) openrouter_api_key="${value}" ;;
    HONCHO_DATABASE_NAME) honcho_database_name="${value}" ;;
  esac
done <"${env_source}"

if [[ -z "${postgres_password}" ]]; then
  echo "ERROR: POSTGRES_PASSWORD is empty in ${env_source}." >&2
  exit 1
fi
if [[ -z "${openrouter_api_key}" ]]; then
  echo "ERROR: OPENROUTER_API_KEY is empty in ${env_source}." >&2
  echo "Set it before installing Honcho (Honcho needs an LLM provider to boot)." >&2
  exit 1
fi

db_conn_uri="postgresql+psycopg://postgres:${postgres_password}@127.0.0.1:5433/${honcho_database_name}"

umask 077
{
  cat <<EOF
# Generated by stack/services/honcho/install.sh — do not edit by hand.
# Re-run the installer to regenerate after stack/prototype-local/.env changes.
LOG_LEVEL=INFO
AUTH_USE_AUTH=false
VECTOR_STORE_TYPE=pgvector

# Database (shared substrate Postgres; honcho DB + pgvector created by
# stack/prototype-local/docker-compose.substrate.yml's postgres-bootstrap).
DB_CONNECTION_URI=${db_conn_uri}

# LLM provider (OpenAI-compatible via OpenRouter).
LLM_OPENAI_COMPATIBLE_BASE_URL=https://openrouter.ai/api/v1
LLM_OPENAI_COMPATIBLE_API_KEY=${openrouter_api_key}
LLM_EMBEDDING_PROVIDER=openrouter

# Feature models (tool-calling capable).
DERIVER_PROVIDER=custom
DERIVER_MODEL=openai/gpt-4o-mini
SUMMARY_PROVIDER=custom
SUMMARY_MODEL=openai/gpt-4o-mini
DREAM_PROVIDER=custom
DREAM_MODEL=openai/gpt-4o-mini
DREAM_DEDUCTION_MODEL=openai/gpt-4o-mini
DREAM_INDUCTION_MODEL=openai/gpt-4o-mini
EOF
  for level in minimal low medium high max; do
    cat <<EOF
DIALECTIC_LEVELS__${level}__PROVIDER=custom
DIALECTIC_LEVELS__${level}__MODEL=openai/gpt-4o-mini
DIALECTIC_LEVELS__${level}__THINKING_BUDGET_TOKENS=0
DIALECTIC_LEVELS__${level}__MAX_TOOL_ITERATIONS=1
EOF
  done
} >"${honcho_env_file}"
chmod 0600 "${honcho_env_file}"

render_unit() {
  local src="$1" dst="$2"
  sed \
    -e "s|@HONCHO_DIR@|${honcho_dir}|g" \
    -e "s|@ENV_FILE@|${honcho_env_file}|g" \
    -e "s|@UV_BIN@|${uv_bin}|g" \
    "${src}" >"${dst}.tmp"
  mv "${dst}.tmp" "${dst}"
}

render_unit "${script_dir}/honcho.service.in"         "${systemd_user_dir}/honcho.service"
render_unit "${script_dir}/honcho-deriver.service.in" "${systemd_user_dir}/honcho-deriver.service"

systemctl --user daemon-reload

cat <<EOF
Installed:
  - ${honcho_env_file}
  - ${systemd_user_dir}/honcho.service
  - ${systemd_user_dir}/honcho-deriver.service

Next:
  systemctl --user enable --now honcho honcho-deriver
  systemctl --user status  honcho honcho-deriver
  curl -fsS http://127.0.0.1:18000/health
EOF
