#!/usr/bin/env bash
#
# Install the Hermes "orchestrator-ceo" profile directory on this host.
#
# Idempotent: re-running is safe. It:
#   - creates /var/lib/hermes/orchestrator-ceo/.hermes/{skills,sessions,logs,memories}
#   - creates /var/lib/paperclip/workspaces/orchestrator-ceo/
#   - renders <profile>/.hermes/config.yaml pointing Hermes at Honcho
#   - renders <profile>/.hermes/honcho.json (workspace=1215-vps, peer=ceo)
#   - renders <profile>/.hermes/.env with:
#       * OPENROUTER_API_KEY (sourced from stack/prototype-local/.env)
#       * HERMES_CEO_CANARY  (fake-secret canary, never leaves the host)
#   - writes a host-only README.md in /var/lib/hermes/orchestrator-ceo/
#
# The profile deliberately lives under /var/lib so that (a) it survives a
# repo re-clone and (b) the Phase D hermes-gateway can chown/chmod it
# independently of the repo. Re-runs are non-destructive: existing
# OPENROUTER_API_KEY / HERMES_CEO_CANARY values are preserved.
#
# Requires sudo for the initial mkdir/chown only; subsequent runs against
# a user-owned tree succeed without sudo. Pass --force to overwrite
# existing config/.env files (e.g. after rotating the canary).
#
# Prereqs:
#   - stack/prototype-local/.env exists with OPENROUTER_API_KEY set
#   - Honcho is reachable at http://127.0.0.1:18000 (see stack/services/honcho/)

set -Eeuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../../.." && pwd)"
env_source="${repo_root}/stack/prototype-local/.env"

profile_root="/var/lib/hermes/orchestrator-ceo"
hermes_home="${profile_root}/.hermes"
workspace_root="/var/lib/paperclip/workspaces/orchestrator-ceo"

force=0
for arg in "$@"; do
  case "${arg}" in
    --force) force=1 ;;
    -h|--help)
      sed -n '2,24p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument '${arg}'." >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "${env_source}" ]]; then
  echo "ERROR: missing ${env_source}; run stack/prototype-local/scripts/init_env.py first." >&2
  exit 1
fi

# -- Parse the stack .env (KEY=VALUE; comments ignored) -----------------------
openrouter_api_key=""
minio_root_password=""
langfuse_host=""
langfuse_public_key=""
langfuse_secret_key=""
while IFS= read -r line; do
  [[ "${line}" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line//[[:space:]]/}" ]] && continue
  key="${line%%=*}"
  value="${line#*=}"
  case "${key}" in
    OPENROUTER_API_KEY) openrouter_api_key="${value}" ;;
    MINIO_ROOT_PASSWORD) minio_root_password="${value}" ;;
    LANGFUSE_HOST) langfuse_host="${value}" ;;
    LANGFUSE_PUBLIC_KEY) langfuse_public_key="${value}" ;;
    LANGFUSE_SECRET_KEY) langfuse_secret_key="${value}" ;;
  esac
done <"${env_source}"

if [[ -z "${openrouter_api_key}" ]]; then
  echo "ERROR: OPENROUTER_API_KEY is empty in ${env_source}." >&2
  exit 1
fi

# MINIO_ROOT_PASSWORD is optional at profile-install time — the
# continuity-plane artifact skills need it, but a fresh prototype-local
# setup may not yet have MinIO running. If absent, skills that need
# MinIO will exit cleanly with a helpful error.

# -- Ensure host directories exist and are owned by the current user ----------
run_sudo() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    echo "ERROR: need root (or sudo) to create ${profile_root} / ${workspace_root}." >&2
    exit 1
  fi
}

need_sudo=0
for p in "${profile_root}" "${workspace_root}"; do
  parent="$(dirname "${p}")"
  if [[ ! -d "${parent}" ]] || [[ ! -w "${parent}" ]]; then
    need_sudo=1
  fi
done

if [[ "${need_sudo}" -eq 1 ]]; then
  run_sudo mkdir -p "${hermes_home}/skills" \
                    "${hermes_home}/sessions" \
                    "${hermes_home}/logs" \
                    "${hermes_home}/memories" \
                    "${workspace_root}"
  run_sudo chown -R "${USER}:${USER}" "${profile_root}" "${workspace_root}"
else
  mkdir -p "${hermes_home}/skills" \
           "${hermes_home}/sessions" \
           "${hermes_home}/logs" \
           "${hermes_home}/memories" \
           "${workspace_root}"
fi

# Group bit: Phase D will add a hermes-gateway group and chgrp this tree to
# it; for now we just leave it 0750 so stray users can't read the canary.
chmod 0750 "${profile_root}" "${workspace_root}"
chmod 0750 "${hermes_home}"

# -- Render ${hermes_home}/config.yaml ----------------------------------------
config_path="${hermes_home}/config.yaml"
if [[ ! -f "${config_path}" ]] || [[ "${force}" -eq 1 ]]; then
  cat >"${config_path}" <<'YAML'
# Generated by stack/services/hermes-gateway/scripts/setup_ceo_profile.sh.
# Re-run with --force to regenerate.
memory:
  provider: honcho
model: openai/gpt-4o-mini
YAML
fi

# -- Render ${hermes_home}/honcho.json ----------------------------------------
honcho_path="${hermes_home}/honcho.json"
if [[ ! -f "${honcho_path}" ]] || [[ "${force}" -eq 1 ]]; then
  cat >"${honcho_path}" <<'JSON'
{
  "baseUrl": "http://127.0.0.1:18000",
  "workspace": "1215-vps",
  "peerName": "ceo",
  "aiPeer": "hermes",
  "enabled": true,
  "recallMode": "hybrid",
  "writeFrequency": "turn",
  "contextCadence": 1,
  "dialecticCadence": 1
}
JSON
fi

# -- Render ${hermes_home}/.env (OPENROUTER_API_KEY + canary) -----------------
env_path="${hermes_home}/.env"
existing_canary=""
if [[ -f "${env_path}" ]]; then
  existing_canary="$(grep -E '^HERMES_CEO_CANARY=' "${env_path}" | head -n1 | cut -d= -f2- || true)"
fi
canary="${existing_canary:-FAKE_CEO_SECRET_DO_NOT_LEAK_1215_KWHK8X2M}"

umask 077
cat >"${env_path}" <<EOF
# Generated by stack/services/hermes-gateway/scripts/setup_ceo_profile.sh.
# HOST-ONLY. Never commit. Re-rendering preserves HERMES_CEO_CANARY.
#
# This file is the profile's secret surface. The Phase D hermes-gateway
# will read it at spawn time and NEVER forward it to Paperclip / the
# broker / Langfuse. A later acceptance test will grep for
# HERMES_CEO_CANARY's value in every hermes-produced artifact; a
# positive match means the secret-handling posture has regressed.
OPENROUTER_API_KEY=${openrouter_api_key}
HERMES_CEO_CANARY=${canary}

# Continuity-plane skill defaults (Phase F). Scripts read these to
# avoid hard-coding endpoints; overriding via CLI flags still works.
BROKER_URL=http://127.0.0.1:8090
MINIO_ENDPOINT=http://127.0.0.1:9010
MINIO_ACCESS_KEY=minio
MINIO_SECRET_KEY=${minio_root_password}
MINIO_ARTIFACTS_BUCKET=artifacts
HERMES_NODE_ID=ceo-orchestrator

# Langfuse observability (Phase G). If Hermes (or any skill) emits
# spans while LANGFUSE_TRACE_ID/LANGFUSE_SESSION_ID are set by the
# gateway at spawn time, the spans will land under the gateway's trace.
# Empty here = Hermes emits nothing to Langfuse, which is fine — the
# gateway still emits 3 lifecycle spans per run on its own.
LANGFUSE_HOST=${langfuse_host}
LANGFUSE_PUBLIC_KEY=${langfuse_public_key}
LANGFUSE_SECRET_KEY=${langfuse_secret_key}
EOF
chmod 0600 "${env_path}"

# Empty skills/ sentinel so future tools can rely on the dir existing.
[[ -f "${hermes_home}/skills/.keep" ]] || : >"${hermes_home}/skills/.keep"

# -- Continuity-plane skills (Phase F) ---------------------------------------
# Rsync the in-repo skill tree into <hermes_home>/skills/continuity-plane/.
# Delete-on-refresh semantics only under continuity-plane/ so we don't
# nuke any hand-authored skills a user dropped next to ours. --force does
# exactly the same thing as a normal run (skills are pure assets; there
# is nothing to preserve, unlike .env).
skills_source="${repo_root}/stack/services/hermes-gateway/skills/continuity-plane"
skills_dest="${hermes_home}/skills/continuity-plane"
if [[ -d "${skills_source}" ]]; then
  mkdir -p "${skills_dest}"
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete \
      --exclude '__pycache__/' \
      --exclude '*.pyc' \
      "${skills_source}/" "${skills_dest}/"
  else
    rm -rf "${skills_dest}"
    mkdir -p "${skills_dest}"
    cp -R "${skills_source}/." "${skills_dest}/"
  fi
  # Scripts must be executable for the SKILL.md instructions to hold.
  find "${skills_dest}" -name '*.py' -not -name '_*.py' -print0 \
    | xargs -0 -r chmod 0755
fi

# -- Host-only README.md ------------------------------------------------------
readme_path="${profile_root}/README.md"
cat >"${readme_path}" <<EOF
# orchestrator-ceo Hermes profile

Host-only directory. Do NOT commit this tree.

Layout:
  .hermes/
    config.yaml       # memory.provider: honcho
    honcho.json       # Honcho workspace="1215-vps", peer="ceo"
    .env              # OPENROUTER_API_KEY + HERMES_CEO_CANARY (600)
    skills/           # populated in Phase F
    sessions/, logs/, memories/

Reproducible installer (in-repo):
  stack/services/hermes-gateway/scripts/setup_ceo_profile.sh
  (pass --force to regenerate config.yaml/honcho.json/.env)

Companion workspace (Paperclip cwd):
  ${workspace_root}

Invoke Hermes against this profile:
  HERMES_HOME=${hermes_home} hermes <command>

The Phase D hermes-gateway will be the only legitimate spawner of
Hermes against this profile; it enforces the profile allowlist and
mints run-scoped env from .env without exposing it to Paperclip.
EOF

# -- Summary ------------------------------------------------------------------
cat <<EOF
Installed:
  - ${hermes_home}/config.yaml
  - ${hermes_home}/honcho.json
  - ${env_path}  (mode 0600)
  - ${hermes_home}/skills/.keep
  - ${hermes_home}/skills/continuity-plane/  (Phase F: broadcast_* + artifact_* skills)
  - ${workspace_root}/
  - ${readme_path}

Smoke (requires Honcho healthy at http://127.0.0.1:18000):
  HERMES_HOME=${hermes_home} \\
    ${repo_root}/modules/hermes-agent/.venv/bin/hermes memory status

Canary (grep this string in any hermes-produced artifact; it MUST NOT appear):
  ${canary}
EOF
